openapi: 3.0.3
info:
  title: Conference Room Booking API
  description: API for managing conference room bookings and events.
  version: 1.0.0

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Invalid credentials

  /auth/logout:
    post:
      summary: User logout
      responses:
        '200':
          description: Successful logout

  /rooms:
    get:
      summary: List all rooms
      responses:
        '200':
          description: List of all rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'

    post:
      summary: Add a new room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '201':
          description: Room created

  /rooms/{roomId}:
    get:
      summary: View room details
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

    put:
      summary: Update room details
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '200':
          description: Room updated

    delete:
      summary: Delete room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Room deleted

  /bookings:
    get:
      summary: List all bookings
      responses:
        '200':
          description: List of all bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

    post:
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created

  /bookings/{bookingId}:
    get:
      summary: View booking details
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'

    put:
      summary: Update booking details
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Booking updated

    delete:
      summary: Cancel booking
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Booking canceled

components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        capacity:
          type: integer
        features:
          type: array
          items:
            type: string

    Booking:
      type: object
      properties:
        id:
          type: string
        roomId:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        numPeople:
          type: integer
        tableSetting:
          type: string
        description:
          type: string

    Event:
      type: object
      properties:
        id:
          type: string
        eventName:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        roomIds:
          type: array
          items:
            type: string
        description:
          type: string
