openapi: 3.0.0
info:
  title: Conference Room Booking System API
  version: 1.0.0
  description: API for managing conference room bookings and availability.
servers:
  - url: /api
paths:
  /rooms:
    get:
      summary: Get all rooms
      responses:
        '200':
          description: List of all rooms
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        capacity:
                          type: integer
                        features:
                          type: array
                          items:
                            type: string
  /rooms/{roomId}:
    get:
      summary: Get details of a specific room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  capacity:
                    type: integer
                  features:
                    type: array
                    items:
                      type: string
                  description:
                    type: string
  /reservations:
    post:
      summary: Create a reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [booking, event]
                roomIds:
                  type: array
                  items:
                    type: string
                date:
                  type: string
                  format: date
                  nullable: true
                startTime:
                  type: string
                  format: time
                  nullable: true
                endTime:
                  type: string
                  format: time
                  nullable: true
                startDate:
                  type: string
                  format: date
                  nullable: true
                endDate:
                  type: string
                  format: date
                  nullable: true
                numPeople:
                  type: integer
                  nullable: true
                tableSetting:
                  type: string
                  nullable: true
                description:
                  type: string
      responses:
        '201':
          description: Reservation created
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservationId:
                    type: string
                  type:
                    type: string
                  status:
                    type: string
    get:
      summary: Get all reservations
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [booking, event]
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: roomId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservations:
                    type: array
                    items:
                      type: object
                      properties:
                        reservationId:
                          type: string
                        type:
                          type: string
                        roomIds:
                          type: array
                          items:
                            type: string
                        date:
                          type: string
                          format: date
                        startDate:
                          type: string
                          format: date
                        endDate:
                          type: string
                          format: date
                        startTime:
                          type: string
                          format: time
                        endTime:
                          type: string
                          format: time
                        status:
                          type: string
  /reservations/{reservationId}:
    get:
      summary: Get reservation details
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reservation details
          content:
            application/json:
              schema:
                type: object
    put:
      summary: Update a reservation
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomIds:
                  type: array
                  items:
                    type: string
                date:
                  type: string
                  format: date
                startTime:
                  type: string
                  format: time
                endTime:
                  type: string
                numPeople:
                  type: integer
                tableSetting:
                  type: string
      responses:
        '200':
          description: Reservation updated
    delete:
      summary: Cancel a reservation
      parameters:
        - name: reservationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reservation canceled
  /rooms/availability/calendar:
    get:
      summary: Fetch room availability for a date range
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: roomId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Room availability for the specified date range
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        availability:
                          type: array
                          items:
                            type: object
                            properties:
                              date:
                                type: string
                                format: date
                              timeSlots:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    startTime:
                                      type: string
                                      format: time
                                    endTime:
                                      type: string
                                      format: time
                                    status:
                                      type: string
                                      enum: [available, reserved]
                                    bookingId:
                                      type: string
                                      nullable: true
